pytest

diff --git a/.github/workflows/pr_basic_checks.yml b/.github/workflows/pr_basic_checks.yml
--- a/.github/workflows/pr_basic_checks.yml
+++ b/.github/workflows/pr_basic_checks.yml
@@ -2,177 +2,179 @@ on:
   pull_request:
 
 jobs:
-  # basic:
-  #   runs-on: ubuntu-latest
-  #   container:
-  #     image: ghcr.io/saheerb/mbed-os-env:master-test
+  basic:
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/saheerb/mbed-os-env:master-test
 
-  #   steps:
-  #     - name: Checkout repo
-  #       uses: actions/checkout@v2
-  #       with:
-  #         fetch-depth: 0
-  #     - 
-  #       name: "file attributes"
-  #       run: |
-  #         git diff --exit-code
-  #     - 
-  #       name: license check existing files
-  #       run: |
-  #         set -x
-  #         ls
-  #         mkdir -p SCANCODE
-  #         git diff --name-only --diff-filter=ad origin/${GITHUB_BASE_REF}.. \
-  #           | ( grep '.\(c\|cpp\|h\|hpp\|py\)$' || true ) \
-  #           | ( grep -v '^tools/test/toolchains/api_test.py' || true ) \
-  #           | while read file; do cp --parents "${file}" SCANCODE; done
-  #         ls SCANCODE
-  #         scancode -l --json-pp scancode.json SCANCODE
-  #         python ./tools/test/travis-ci/scancode-evaluate.py scancode.json || true
-  #         cat scancode-evaluate.log
-  #         COUNT=$(cat scancode-evaluate.log | grep 'File:' | grep -v 'SPDX' | wc -l) || true
-  #         if [ $COUNT = 0 ]; then
-  #           echo "License check OK";
-  #           true;
-  #         else
-  #           echo "License check failed, please review license issues found in modified files";
-  #           false;
-  #         fi
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - 
+        name: "file attributes"
+        run: |
+          git diff --exit-code
+      - 
+        name: license check existing files
+        shell: bash
+        run: |
+          set -x
+          ls
+          mkdir -p SCANCODE
+          git diff --name-only --diff-filter=ad origin/${GITHUB_BASE_REF}.. \
+            | ( grep '.\(c\|cpp\|h\|hpp\|py\)$' || true ) \
+            | ( grep -v '^tools/test/toolchains/api_test.py' || true ) \
+            | while read file; do cp --parents "${file}" SCANCODE; done
+          ls SCANCODE
+          scancode -l --json-pp scancode.json SCANCODE
+          python ./tools/test/travis-ci/scancode-evaluate.py scancode.json || true
+          cat scancode-evaluate.log
+          COUNT=$(cat scancode-evaluate.log | grep 'File:' | grep -v 'SPDX' | wc -l) || true
+          if [ $COUNT == 0 ]; then
+            echo "License check OK";
+            true;
+          else
+            echo "License check failed, please review license issues found in modified files";
+            false;
+          fi
 
-  #     - 
-  #       name: license check new files
-  #       run: |
-  #         mkdir -p SCANCODE_NEW_FILES
-  #         git diff --name-only --diff-filter=A origin/${GITHUB_BASE_REF}.. \
-  #           | ( grep '.\(c\|cpp\|h\|hpp\|py\)$' || true ) \
-  #           | ( grep -v '^tools/test/toolchains/api_test.py' || true ) \
-  #           | while read file; do cp --parents "${file}" SCANCODE_NEW_FILES; done
-  #         ls SCANCODE_NEW_FILES
-  #         scancode -l --json-pp scancode.json SCANCODE_NEW_FILES
-  #         python ./tools/test/travis-ci/scancode-evaluate.py scancode.json || true
-  #         cat scancode-evaluate.log
-  #         COUNT=$(cat scancode-evaluate.log | grep 'File:' | grep -v 'SPDX' | wc -l) || true
-  #         if [ $COUNT = 0 ]; then
-  #           echo "License check OK";
-  #           true;
-  #         else
-  #           echo "License check failed, please review license issues found in new files";
-  #           false;
-  #         fi
+      - 
+        name: license check new files
+        shell: bash
+        run: |
+          mkdir -p SCANCODE_NEW_FILES
+          git diff --name-only --diff-filter=A origin/${GITHUB_BASE_REF}.. \
+            | ( grep '.\(c\|cpp\|h\|hpp\|py\)$' || true ) \
+            | ( grep -v '^tools/test/toolchains/api_test.py' || true ) \
+            | while read file; do cp --parents "${file}" SCANCODE_NEW_FILES; done
+          ls SCANCODE_NEW_FILES
+          scancode -l --json-pp scancode.json SCANCODE_NEW_FILES
+          python ./tools/test/travis-ci/scancode-evaluate.py scancode.json || true
+          cat scancode-evaluate.log
+          COUNT=$(cat scancode-evaluate.log | grep 'File:' | grep -v 'SPDX' | wc -l) || true
+          if [ $COUNT == 0 ]; then
+            echo "License check OK";
+            true;
+          else
+            echo "License check failed, please review license issues found in new files";
+            false;
+          fi
 
-  #     - 
-  #       name: "UTF-8 Check"
-  #       run: |
-  #         # Make sure we're not introducing any text which is not UTF-8 encoded
-  #         git diff origin/${GITHUB_BASE_REF} -U0 | ( grep -a '^+' || true ) | ( ! grep -axv '.*' )
+      - 
+        name: "UTF-8 Check"
+        run: |
+          # Make sure we're not introducing any text which is not UTF-8 encoded
+          git diff origin/${GITHUB_BASE_REF} -U0 | ( grep -a '^+' || true ) | ( ! grep -axv '.*' )
 
-  #     - 
-  #       name: "include check"
-  #       run: |
-  #         ! git grep '^#include\s["'"']mbed.h['"'"]$' -- '*.c' '*.h' '*.cpp' '*.hpp' \
-  #             ':!*platform_mbed.h' ':!*TESTS/*' ':!TEST_APPS/' ':!UNITTESTS/' \
-  #             ':!*tests/*' ':!*targets/*' ':!*TARGET_*' ':!*unsupported/*' \
-  #             ':!*events/tests/*' ':!*drivers/tests/*'
+      - 
+        name: "include check"
+        run: |
+          ! git grep '^#include\s["'"']mbed.h['"'"]$' -- '*.c' '*.h' '*.cpp' '*.hpp' \
+              ':!*platform_mbed.h' ':!*TESTS/*' ':!TEST_APPS/' ':!UNITTESTS/' \
+              ':!*tests/*' ':!*targets/*' ':!*TARGET_*' ':!*unsupported/*' \
+              ':!*events/tests/*' ':!*drivers/tests/*'
 
-  #     - 
-  #       name: astyle checks
-  #       run: |
-  #         git diff --name-only --diff-filter=d origin/${GITHUB_BASE_REF} \
-  #           | ( grep '.*\.\(c\|cpp\|h\|hpp\)$' || true ) \
-  #           | ( grep -v -f .codecheckignore || true ) \
-  #           | while read file; do astyle -n --options=.astylerc "${file}"; done
-  #         git diff --exit-code --diff-filter=d --color
+      - 
+        name: astyle checks
+        run: |
+          git diff --name-only --diff-filter=d origin/${GITHUB_BASE_REF} \
+            | ( grep '.*\.\(c\|cpp\|h\|hpp\)$' || true ) \
+            | ( grep -v -f .codecheckignore || true ) \
+            | while read file; do astyle -n --options=.astylerc "${file}"; done
+          git diff --exit-code --diff-filter=d --color
 
-  #     - 
-  #       name: spell checks
-  #       run: |
-  #         apt-get update -y
-  #         apt-get install -y aspell
-  #         ./tools/test/travis-ci/doxy-spellchecker/spell.sh drivers .codecheckignore
-  #         ./tools/test/travis-ci/doxy-spellchecker/spell.sh platform .codecheckignore
-  #         ./tools/test/travis-ci/doxy-spellchecker/spell.sh events .codecheckignore
-  #         ./tools/test/travis-ci/doxy-spellchecker/spell.sh rtos .codecheckignore
-  #         ./tools/test/travis-ci/doxy-spellchecker/spell.sh connectivity/netsocket .codecheckignore
+      - 
+        name: spell checks
+        run: |
+          apt-get update -y
+          apt-get install -y aspell
+          ./tools/test/travis-ci/doxy-spellchecker/spell.sh drivers .codecheckignore
+          ./tools/test/travis-ci/doxy-spellchecker/spell.sh platform .codecheckignore
+          ./tools/test/travis-ci/doxy-spellchecker/spell.sh events .codecheckignore
+          ./tools/test/travis-ci/doxy-spellchecker/spell.sh rtos .codecheckignore
+          ./tools/test/travis-ci/doxy-spellchecker/spell.sh connectivity/netsocket .codecheckignore
 
-  #     - 
-  #       name: doxygen
-  #       run: |
-  #         apt-get install -y ccache
-  #         ccache -s
-  #         mkdir BUILD
-  #         # Assert that the Doxygen build produced no warnings.
-  #         # The strange command below asserts that the Doxygen command had an
-  #         # output of zero length
-  #         doxygen doxyfile_options 2>&1
-  #         # Once Mbed OS has been fixed, enable the full test by replacing the top line with this:
-  #         # - ( ! doxygen doxyfile_options 2>&1 | grep . )
-  #         # Assert that all binary libraries are named correctly
-  #         # The strange command below asserts that there are exactly 0 libraries
-  #         # that do not start with lib
-  #         find "(" -name "*.a" -or -name "*.ar" ")" -and -not -name "lib*" |
-  #         tee BUILD/badlibs |
-  #         sed -e "s/^/Bad library name found: /" && [ ! -s BUILD/badlibs ]
-  #         # Assert that all assembler files are named correctly
-  #         # The strange command below asserts that there are exactly 0 libraries
-  #         # that do end with .s
-  #         find  -name "*.s" | tee BUILD/badasm |
-  #         sed -e "s/^/Bad Assembler file name found: /" && [ ! -s BUILD/badasm ]
+      - 
+        name: doxygen
+        run: |
+          apt-get install -y ccache
+          ccache -s
+          mkdir BUILD
+          # Assert that the Doxygen build produced no warnings.
+          # The strange command below asserts that the Doxygen command had an
+          # output of zero length
+          doxygen doxyfile_options 2>&1
+          # Once Mbed OS has been fixed, enable the full test by replacing the top line with this:
+          # - ( ! doxygen doxyfile_options 2>&1 | grep . )
+          # Assert that all binary libraries are named correctly
+          # The strange command below asserts that there are exactly 0 libraries
+          # that do not start with lib
+          find "(" -name "*.a" -or -name "*.ar" ")" -and -not -name "lib*" |
+          tee BUILD/badlibs |
+          sed -e "s/^/Bad library name found: /" && [ ! -s BUILD/badlibs ]
+          # Assert that all assembler files are named correctly
+          # The strange command below asserts that there are exactly 0 libraries
+          # that do end with .s
+          find  -name "*.s" | tee BUILD/badasm |
+          sed -e "s/^/Bad Assembler file name found: /" && [ ! -s BUILD/badasm ]
 
-  # python-tests:
-  #   runs-on: ubuntu-latest
+  python-tests:
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #     -
-  #       name: Checkout repo
-  #       uses: actions/checkout@v2
+    steps:
+      -
+        name: Checkout repo
+        uses: actions/checkout@v2
 
 
-  #     - uses: actions/setup-python@v2
-  #       with:
-  #         python-version: '3.7'
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.7'
 
-  #     -
-  #       name: install dependencies
-  #       run: |
-  #         pip install -r requirements.txt
-  #         pip install icetea pytz
-  #         pip install mock==2.0.0 attrs==19.1.0 pytest==3.3.0 'pylint>=1.9,<2' 'hypothesis>=3,<4' 'coverage>=4.5,<5'
+      -
+        name: install dependencies
+        run: |
+          pip install -r requirements.txt
+          pip install icetea pytz
+          pip install mock==2.0.0 attrs==19.1.0 pytest==3.3.0 'pylint>=1.9,<2' 'hypothesis>=3,<4' 'coverage>=4.5,<5'
 
-  #     -
-  #       name: pytest
-  #       run: |
-  #         PYTHONPATH=. coverage run -a -m pytest tools/test
-  #         python tools/test/pylint.py
-  #         coverage run -a tools/project.py -S | sed -n '/^Total/p'
-  #         coverage html
+      -
+        name: pytest
+        run: |
+          PYTHONPATH=. coverage run -a -m pytest tools/test
+          python tools/test/pylint.py
+          coverage run -a tools/project.py -S | sed -n '/^Total/p'
+          coverage html
 
-  # Pin-validation:
-  #   runs-on: ubuntu-latest
+  Pin-validation:
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #     -
-  #       name: Checkout repo
-  #       uses: actions/checkout@v2
-  #       with:
-  #         fetch-depth: 0
+    steps:
+      -
+        name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
-  #     - uses: actions/setup-python@v2
-  #       with:
-  #         python-version: '3.7'
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.7'
 
-  #     -
-  #       name: install dependencies
-  #       run: |
-  #         pip install tabulate argparse
+      -
+        name: install dependencies
+        run: |
+          pip install tabulate argparse
 
-  #     -
-  #       name: validate pins
-  #       run: |
-  #         set -x
-  #         git diff --name-only --diff-filter=d origin/${GITHUB_BASE_REF} \
-  #           | ( grep '.*[\\|\/]PinNames.h$' || true ) \
-  #           | while read file; do python ./hal/tests/pinvalidate/pinvalidate.py -vfp "${file}"; done
-  #         git diff --exit-code --diff-filter=d --color
+      -
+        name: validate pins
+        run: |
+          set -x
+          git diff --name-only --diff-filter=d origin/${GITHUB_BASE_REF} \
+            | ( grep '.*[\\|\/]PinNames.h$' || true ) \
+            | while read file; do python ./hal/tests/pinvalidate/pinvalidate.py -vfp "${file}"; done
+          git diff --exit-code --diff-filter=d --color
 
   cmake-check:
     env: 
